[package]
name = "github-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
env_logger = "0.11.2"
log = "0.4.21"
serde = { version = "1.0.197", feature = ["derive"] }
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["io-util", "io-std", "macros", "rt-multi-thread", "process"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
