[package]
name = "github-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
dashmap = "5.5.3"
env_logger = "0.11.2"
futures = "0.3.30"
log = "0.4.21"
mio = "0.8.11"
octocrab = "0.37.0"
reqwest = { version = "0.12.2", default-features = false, features = ["rustls-tls"] }
ropey = "1.6.1"
select = "0.6.0"
serde = "1.0.197"
serde_json = "1.0.114"
tokio = { version = "1.37.0", features = ["io-util", "io-std", "macros", "rt-multi-thread", "process", "time"] }
tower-lsp = "0.20.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
tokio = { version = "1.37.0", features = ["io-util", "io-std", "macros", "rt-multi-thread", "process"] }
